package com.testlang;

import java_cup.runtime.*;
// Import all of our new AST node classes

// Define terminals (tokens from the lexer)
terminal CONFIG, LET, TEST, GET, POST, PUT, DELETE, EXPECT, STATUS, HEADER, BODY, CONTAINS, BASE_URL;
terminal String IDENT, STRING, NUMBER;
terminal EQ, LBRACE, RBRACE, SEMI;

// Define non-terminals AND the Java object they will return
non terminal ProgramNode      program;
non terminal StatementNode    statement;
non terminal LetNode          let_decl;
non terminal TestNode         test_block;
non terminal ConfigNode       config_block;


// The grammar rules start here
program ::=
    program:p statement:s
    {:
        // JAVA CODE: Add the statement to the program's list
        p.addStatement(s);
        RESULT = p;
    :}
    |
    /* empty */
    {:
        // JAVA CODE: Create a new, empty ProgramNode
        RESULT = new ProgramNode();
    :}
    ;

statement ::=
    let_decl:ld
    {:
        // Pass the LetNode object up
        RESULT = ld;
    :}
    | test_block:tb
    {:
        // Pass the TestNode object up
        RESULT = tb;
    :}
    | config_block:cb
    {:
        RESULT = cb;
    :}
    ;

// Split into TWO separate production rules
let_decl ::=
    LET IDENT:name EQ STRING:val SEMI
    {:
        // JAVA CODE: Create a new LetNode and return it
        RESULT = new LetNode(name, val);
    :}
    |
    LET IDENT:name EQ NUMBER:val SEMI
    {:
        // JAVA CODE: Create a new LetNode and return it
        RESULT = new LetNode(name, val);
    :}
    ;

test_block ::= TEST IDENT:name LBRACE RBRACE
    {:
        // JAVA CODE: Create a new TestNode and return it
        RESULT = new TestNode(name);
    :}
    ;

// This new rule matches: config { base_url = "http://url"; }
config_block ::= CONFIG LBRACE BASE_URL EQ STRING:url SEMI RBRACE
    {:
        // Create a new ConfigNode and return it
        RESULT = new ConfigNode(url);
    :}
    ;